/** Consumer-facing RV manufacturers and the model lines shoppers actually ask for. */

const ALIASES: Record<string, string> = {
  Thor: "Thor Motor Coach",
};

const RV_MODELS_BY_MAKE: Record<string, readonly string[]> = {
  Adventurer: ["80RB", "86FB", "89RB", "901SB", "910DB"],
  Airstream: [
    "Atlas",
    "Bambi",
    "Basecamp",
    "Caravel",
    "Classic",
    "Cruiser",
    "Excella",
    "Flying Cloud",
    "Globetrotter",
    "International",
    "Interstate",
    "Land Yacht",
    "Pan America",
    "Pottery Barn",
    "Rangeline",
    "REI",
    "Studio",
    "Tommy Bahama",
    "Trade Wind",
  ],
  "Alliance RV": ["Avenue", "Delta", "Paradigm", "Valor"],
  Alfa: ["Gold", "Ideal", "See Ya", "Toyhouse"],
  Aliner: ["Classic", "Evolution", "LXE", "Ranger", "Scout"],
  "American Coach": [
    "American Dream",
    "American Eagle",
    "American Heritage",
    "American Patriot",
    "American Revolution",
    "American Tradition",
  ],
  ATC: ["Game Changer", "PLA 350", "PLA 700", "Stacker"],
  Beaver: ["Contessa", "Marquis", "Monterey", "Patriot", "Santiam"],
  Bigfoot: ["1500", "2500", "3000", "Travel Trailer", "Truck Camper"],
  "Brinkley RV": ["Model G", "Model I", "Model Z"],
  Carriage: ["Cabriolet", "Cameo", "Carri-Lite"],
  Casita: ["Freedom", "Heritage", "Independence", "Liberty", "Spirit", "Spirit Deluxe"],
  Chinook: ["Bayside", "Countryside", "Maverick"],
  "Coach House": ["Arriva", "Platinum", "Platinum III"],
  Coachmen: [
    "Adrenaline",
    "Apex",
    "Beyond",
    "Brookstone",
    "Catalina",
    "Chaparral",
    "Clipper",
    "Concord",
    "Cross Trek",
    "Encore",
    "Freedom Express",
    "Freelander",
    "Galleria",
    "Leprechaun",
    "Mirada",
    "Nova",
    "Prism",
    "Pursuit",
    "Remote",
    "Spirit",
    "Sportscoach",
    "Viking",
  ],
  Coleman: ["Lantern", "Lantern LT", "Rubicon"],
  "Country Coach": [
    "Affinity",
    "Allure",
    "Inspire",
    "Intrigue",
    "Lexa",
    "Magna",
    "Rhapsody",
    "Tribute",
    "Veranda",
  ],
  CrossRoads: ["Cameo", "Cruiser", "Hampton", "Slingshot", "Volante", "Zinger"],
  "Cruiser RV": ["Avenir", "Embrace", "MPG", "Radiance", "Shadow Cruiser", "Stryker", "Twilight"],
  Damon: ["Astoria", "Challenger", "Daybreak", "Intruder", "Outlaw", "Tuscany"],
  DRV: ["Elite Suites", "Full House", "Luxetica", "Mobile Suites", "Tradition"],
  Dutchmen: [
    "Aerolite",
    "Aspen Trail",
    "Astoria",
    "Atlas",
    "Coleman Lantern",
    "Colorado",
    "Kodiak",
    "Rubicon",
    "Voltage",
    "Yukon",
  ],
  Dynamax: ["DX3", "Europa", "Force", "Force HD", "Isata 3", "Isata 5", "Isata 6", "Rev"],
  "East to West": ["Ahara", "Alta", "Blackthorn", "Della Terra", "Entrada", "Silver Lake", "Tandara"],
  Entegra: [
    "Accolade",
    "Accolade XL",
    "Anthem",
    "Aspire",
    "Condor",
    "Cornerstone",
    "Emblem",
    "Esteem",
    "Ethos",
    "Ethos Li",
    "Launch",
    "Odyssey",
    "Qwest",
    "Reatta",
    "Reatta XL",
    "Vision",
    "Vision XL",
  ],
  Escape: ["5.0", "17", "19", "21"],
  Featherlite: ["Featherlite", "Vantare"],
  Fleetwood: [
    "Bounder",
    "Discovery",
    "Discovery LXE",
    "Excursion",
    "Expedition",
    "Flair",
    "Flex",
    "Fortis",
    "Frontier",
    "Irok",
    "Jamboree",
    "Pace Arrow",
    "Southwind",
    "Terra",
    "Tioga",
  ],
  Foretravel: ["Grand Villa", "IC", "IH", "Nimbus", "Realm"],
  "Forest River": [
    "Arctic Wolf",
    "Aurora",
    "Berkshire",
    "Berkshire XL",
    "Cardinal",
    "Cedar Creek",
    "Charleston",
    "Cherokee Alpha Wolf",
    "Cherokee Grey Wolf",
    "Cherokee Wolf Pack",
    "Cherokee Wolf Pup",
    "Flagstaff Classic",
    "Flagstaff E-Pro",
    "Flagstaff High Wall",
    "Flagstaff Micro Lite",
    "Flagstaff Super Lite",
    "Forester",
    "FR3",
    "Georgetown",
    "Ibex",
    "Impression",
    "Legacy",
    "No Boundaries",
    "Ozark",
    "RiverStone",
    "Rockwood Geo Pro",
    "Rockwood High Wall",
    "Rockwood Mini Lite",
    "Rockwood Roo",
    "Rockwood Signature",
    "Rockwood Ultra Lite",
    "R-Pod",
    "Sabre",
    "Salem Cruise Lite",
    "Salem FSX",
    "Salem Hemisphere",
    "Sandpiper",
    "Shockwave",
    "Sierra",
    "Sunseeker",
    "Surveyor",
    "Vengeance",
    "Vibe",
    "Wildwood",
    "Wildwood FSX",
    "Wildwood Heritage Glen",
    "Wildwood Lodge",
    "Wildwood X-Lite",
    "Work and Play",
    "XLR",
  ],
  "Four Wheel Campers": ["Fleet", "Grandby", "Hawk", "Pop-Up", "Project M", "Raven"],
  "Genesis Supreme": ["Extra", "Genesis Supreme", "Vortex"],
  "Grand Design": [
    "Imagine",
    "Imagine AIM",
    "Imagine XLS",
    "Influence",
    "Lineage",
    "Momentum",
    "Reflection",
    "Reflection 100 Series",
    "Serenova",
    "Solitude",
    "Transcend",
    "Transcend Xplor",
  ],
  "Grech RV": ["Strada", "Strada-ion", "Turismo", "Turismo-ion"],
  "Gulf Stream": [
    "Ameri-Lite",
    "BT Cruiser",
    "Canyon Trail",
    "Conquest",
    "Envision",
    "Friendship",
    "Innsbruck",
    "Kingsport",
    "Northern Express",
    "Sedona",
    "Streamlite",
    "Trailmaster",
    "Vintage Cruiser",
    "Yellowstone",
  ],
  "Happier Camper": ["HC1", "Traveler"],
  Heartland: [
    "Bighorn",
    "Bighorn Traveler",
    "Corterra",
    "Cyclone",
    "ElkRidge",
    "Fuel",
    "Gravity",
    "Landmark",
    "Lithium",
    "Mallard",
    "Milestone",
    "North Trail",
    "Pioneer",
    "Road Warrior",
    "Sundance",
    "Torque",
    "Wilderness",
  ],
  "Highland Ridge": ["Light", "Mesa Ridge", "Open Range", "Range Lite", "Roamer"],
  "Holiday Rambler": [
    "Admiral",
    "Alumascape",
    "Armada",
    "Augusta",
    "Eclipse",
    "Endeavor",
    "Endeavor XE",
    "Imperial",
    "Invicta",
    "Nautica",
    "Navigator",
    "Neptune",
    "Scepter",
    "Vacationer",
  ],
  Host: ["Camping Trailer", "Cascade", "Everest", "Mammoth"],
  inTech: ["Explore", "Flyer", "Luna", "Magnolia", "O-V-R", "Sol", "Terra"],
  Itasca: [
    "Cambria",
    "Ellipse",
    "Impulse",
    "Meridian",
    "Navion",
    "Reyo",
    "Solei",
    "Spirit",
    "Suncruiser",
    "Sunova",
  ],
  Jayco: [
    "Alante",
    "Comet",
    "Eagle",
    "Eagle HT",
    "Embark",
    "Greyhawk",
    "Greyhawk Prestige",
    "Hummingbird",
    "Jay Feather",
    "Jay Feather Micro",
    "Jay Flight",
    "Jay Flight SLX",
    "Jay Sport",
    "Melbourne",
    "Melbourne Prestige",
    "North Point",
    "Octane",
    "Pinnacle",
    "Precept",
    "Precept Prestige",
    "Redhawk",
    "Seismic",
    "Seneca",
    "Seneca XT",
    "Solstice",
    "Swift",
    "Talon",
    "Terrain",
    "White Hawk",
  ],
  Keystone: [
    "Alpine",
    "Arcadia",
    "Avalanche",
    "Bullet",
    "Carbon",
    "Cougar",
    "Cougar Half-Ton",
    "Fuzion",
    "Hideout",
    "Impact",
    "Laredo",
    "Montana",
    "Montana High Country",
    "Outback",
    "Passport",
    "Premier",
    "Raptor",
    "Residence",
    "Retreat",
    "Springdale",
    "Sprinter",
  ],
  Komfort: ["Komfort"],
  KZ: [
    "Connect",
    "Connect C",
    "Connect SE",
    "Durango",
    "Durango Gold",
    "Durango Half-Ton",
    "Escape",
    "Ridgeway",
    "Sidewinder",
    "Spree",
    "Sportsmen",
    "Sportsmen Classic",
    "Sportster",
    "Venom",
  ],
  Lance: [
    "650",
    "825",
    "855",
    "960",
    "975",
    "1062",
    "1172",
    "1475",
    "1575",
    "1685",
    "1985",
    "1995",
    "2185",
    "2285",
    "2375",
    "2445",
    "2465",
  ],
  "Leisure Travel Vans": ["Serenity", "Unity", "Wonder"],
  "Liberty Coach": ["Liberty"],
  Luxe: ["Elite", "Gold"],
  Marathon: ["Marathon"],
  "Midwest Automotive Designs": ["Legend", "Lounge", "Passage", "Unity"],
  Monaco: [
    "Camelot",
    "Cayman",
    "Cayman XL",
    "Diplomat",
    "Dynasty",
    "Executive",
    "Knight",
    "LaPalma",
    "Monarch",
    "Signature",
    "Windsor",
  ],
  "National RV": ["Dolphin", "Sea Breeze", "Surf Side", "Tradewinds", "Tropi-Cal"],
  Newell: ["Classic", "Newell", "P50"],
  Newmar: [
    "Bay Star",
    "Bay Star Sport",
    "Canyon Star",
    "Dutch Star",
    "Essex",
    "King Aire",
    "Kountry Star",
    "London Aire",
    "Mountain Aire",
    "New Aire",
    "Super Star",
    "Supreme Aire",
    "Ventana",
  ],
  "Northern Lite": ["8-11", "9-6", "10-2"],
  Northwood: ["Arctic Fox", "Desert Fox", "Fox Mountain", "Nash", "Snow River"],
  nuCamp: ["Barefoot", "Cirrus 620", "Cirrus 820", "TAB 320", "TAB 400", "TAG"],
  NuWa: ["Discovery", "Hitchhiker", "Snowbird"],
  "Oliver Travel Trailers": ["Legacy Elite", "Legacy Elite II"],
  Opus: ["OP Lite", "OP4", "OP15"],
  "Outdoors RV": ["Backcountry", "Black Stone", "Creek Side", "Glacier Peak", "Timber Ridge"],
  Palomino: ["Backpack", "Columbus", "PaloMini", "Puma", "Real-Lite", "SolAire"],
  "Phoenix Cruiser": ["2100", "2350", "2552", "2910", "3100"],
  "Pleasure-Way": ["Ascent", "Lexor", "Ontour", "Plateau", "Rekon", "Tofino"],
  Prevost: ["H3-45", "H3-45 VIP", "X3-45", "XLII"],
  "Prime Time": ["Avenger", "Crusader", "Fury", "Lacrosse", "Navi", "Sanibel", "Tracer"],
  Redwood: ["Redwood"],
  Renegade: ["Classic", "Explorer", "Ikon", "Valencia", "Veracruz", "Verona", "Vienna", "XL"],
  "Riverside RV": ["Intrepid", "Retro", "White Water", "Xplorer"],
  Roadtrek: ["Chase", "Play", "RS Adventurous", "SS Agile", "Zion", "Zion SRT"],
  Safari: ["Cheetah", "Ivory", "Panther", "Simba", "Trek"],
  "Safari Condo": ["Alto"],
  Scamp: ["13", "16", "19"],
  Shasta: ["Airflyte", "I-5", "Oasis", "Phoenix", "Revere"],
  Skyline: ["Aljo", "Bobcat", "Layton", "Nomad", "Walkabout", "Weekender"],
  Sportsmobile: ["Classic", "Sprinter", "Transit"],
  Starcraft: ["AR-ONE", "Autumn Ridge", "GPS", "Launch", "Super Lite", "Telluride"],
  "Storyteller Overland": ["Beast Mode", "Classic Mode", "Mystic", "Stealth Mode"],
  SunnyBrook: ["Brookside", "Mobile Scout", "Sunset Creek", "Titan"],
  "Sunset Park RV": ["Rush", "Sun Lite", "Sunray"],
  Taxa: ["Cricket", "Mantis", "Tiger Moth"],
  "Thor Motor Coach": [
    "ACE",
    "Aria",
    "Axis",
    "Challenger",
    "Chateau",
    "Compass",
    "Dazzle",
    "Delano",
    "Four Winds",
    "Freedom Elite",
    "Gemini",
    "Hurricane",
    "Inception",
    "Magnitude",
    "Miramar",
    "Omni",
    "Outlaw",
    "Palazzo",
    "Pasadena",
    "Quantum",
    "Resonate",
    "Rize",
    "Scope",
    "Sequence",
    "Tellaro",
    "Tiburon",
    "Tranquility",
    "Twist",
    "Vegas",
    "Venetian",
    "Windsport",
  ],
  Tiffin: [
    "Allegro",
    "Allegro Bay",
    "Allegro Bus",
    "Allegro Breeze",
    "Allegro Red",
    "Byway",
    "GH1",
    "Open Road",
    "Phaeton",
    "Wayfarer",
    "Zephyr",
  ],
  "Travel Lite": ["Idea", "Rove Lite", "Super Lite", "Truck Camper"],
  "Travel Supreme": ["Envoy", "Select"],
  Vanleigh: ["Ambition", "Beacon", "PineCrest", "Vilano"],
  "Venture RV": ["Sonic", "SportTrek", "Stratus", "Sunset Trail"],
  Winnebago: [
    "Access",
    "Adventurer",
    "Boldt",
    "Ekko",
    "Era",
    "Forza",
    "Hike",
    "Horizon",
    "Inspire",
    "Intent",
    "Journey",
    "Micro Minnie",
    "Minnie",
    "Minnie Winnie",
    "Navion",
    "Porto",
    "Revel",
    "Solis",
    "Sunstar",
    "Thrive",
    "Tour",
    "Travato",
    "View",
    "Vista",
    "Voyage",
  ],
};

export const NOT_SURE = "Not sure yet";
export const OTHER = "Other";

export const RV_MAKES = Object.keys(RV_MODELS_BY_MAKE).sort((a, b) =>
  a.localeCompare(b),
);

export const SEARCH_MAKES = [...RV_MAKES, ...Object.keys(ALIASES)].sort(
  (a, b) => b.length - a.length,
);

export function canonicalMake(make: string): string {
  const trimmed = make.trim();
  return ALIASES[trimmed] ?? trimmed;
}

export function isKnownMake(make: string): boolean {
  return Object.prototype.hasOwnProperty.call(RV_MODELS_BY_MAKE, canonicalMake(make));
}

export function modelsForMake(make: string): string[] {
  const models = RV_MODELS_BY_MAKE[canonicalMake(make)];
  if (!models) return [];
  return [...models].sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
}

export function rvYears(oldest = 1980): string[] {
  const newest = new Date().getFullYear() + 1;
  const years: string[] = [];
  for (let year = newest; year >= oldest; year -= 1) {
    years.push(String(year));
  }
  return years;
}
